version: "3.7"

services:
  image: mariadb:10.4.6
  hostname: mariadb3.weave.local
  container_name: mariadb3
  replicas: 1
  environment:
    - MYSQL_ROOT_PASSWORD: root_password
    - MYSQL_DATABASE: mydb
    - MYSQL_USER: eavictor
    - MYSQL_PASSWORD: eavictor_password
  ports:
    - "3306:3306"
  expose:
    - "4444"
    - "4567"
    - "4568"
  volumes:
    - type: bind
      source: /home/eavictor/docker_mariadb_galera_cluster/mariadb.cnf
      target: /etc/mysql/conf.d/my_custom.cnf
    - type: bind
      source: /home/eavictor/db_data
      target: /var/lib/mysql

  networks:
    - default

networks:
  default:
    external:
      name: weave